
name: tests
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.13
              uses: actions/setup-go@v1
              with:
                  go-version: 1.13
            - name: Check out code into the Go module directory
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1
                  path: go/src/github.com/guilhermehubner/k8s-bluegreen
            - name: GolangCI-Lint
              run: |
                  curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0
                  ./bin/golangci-lint run --enable golint
            - name: Build
              run: go build